# This workflow will build a Java project with Maven 

name: Java CI with Maven

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{matrix.os}}
    env: 
      workdir: myApp
    strategy:
      matrix:
        include:
          - java: 8
            additional-maven-args: "-Pjacoco -DrepoToken=$COVERALLS_REPO_TOKENcoveralls:report"
          - java: 11
        os: [ubuntu-latest, macos-latest, windows-latest]
        
    name: Build with Java ${{ matrix.java }} on ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: ${{matrix.java}}
    - name: Cache Maven packages
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2${{ hashFiles('**//pom.xml', '**/*.yml') }}
        restore-keys: ${{ runner.os }}-m2-
      uses: actions/cache@v2.1.8
    - name: Build with Maven
      run: >
        mvn verify ${{ matrix.additional-maven-args }}
        surefire-report:report-only site:site -DgenerateReports=false
      working-directory: ${{ workdir }}
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
      if: ${{ always() }}
    - name: Generate JUnit Report 
      run: >
        mvn -f surefire-report:report-only site:site -DgenerateReports=false
      working-directory: ${{ workdir }}
    - uses: actions/upload-artifact@v2 
      if: ${{ always() }}
      with:
        name: surefire-report-jdk-${{ matrix.java }} 
        path: '**/target/site'
        
        
