# This workflow will build a Java project with Maven 

name: Java CI with Maven in Linux

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.7.0
    - name: Setup Java JDK
      uses: actions/setup-java@v3.10.0
      with:
        distribution: 'temurin'
        java-version: 1.8
    - name: Cache
      uses: actions/cache@v2.1.8
    - name: Build with Maven
      run: mvn -f myApp/pom.xml clean verify

